sonobuoy-config:
  description: Running E2E tests for AI Conformance via Sonobuoy to answer the self-certification
    questionnaire template in https://github.com/cncf/ai-conformance.
  driver: Job
  plugin-name: ai-conformance
  result-format: raw
  source-url: https://raw.githubusercontent.com/carlory/sonobuoy-plugins/master/ai-conformance/plugin.yaml
spec:
  args:
  - -c
  - go tool test2json ./e2e.test -test.v | tee ${SONOBUOY_RESULTS_DIR}/out.json ;
    echo ${SONOBUOY_RESULTS_DIR}/out.json > ${SONOBUOY_RESULTS_DIR}/done
  command:
  - bash
  image: ghcr.io/carlory/sonobuoy-plugins/ai-conformance:8c80a65-dirty
  name: plugin

