kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
# Enable CDI as described in
# https://github.com/container-orchestrated-devices/container-device-interface#containerd-configuration
- |-
  [plugins."io.containerd.grpc.v1.cri"]
    enable_cdi = true
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    scheduler:
        extraArgs:
          v: "5"
          vmodule: "allocator=6,dynamicresources=6" # structured/allocator.go, DRA scheduler plugin
    controllerManager:
        extraArgs:
          v: "5"
          vmodule: "controller=6" # resourceclaim/controller.go - should have renamed it when copying the controller it was based on!
    apiServer:
        extraArgs:
          runtime-config: "resource.k8s.io/v1alpha3=true,resource.k8s.io/v1beta1=true,resource.k8s.io/v1beta2=true"
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "5"
- role: worker
  image: kindest/node:v1.34.0
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "5"
        node-labels: "run.ai/simulated-gpu-node-pool=default"
- role: worker
  image: kindest/node:v1.34.0
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "5"
        node-labels: "run.ai/simulated-gpu-node-pool=default"