kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-ai-conformance
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
- role: worker
  image: kindest/node:v1.34.0
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "run.ai/simulated-gpu-node-pool=default"
- role: worker
  image: kindest/node:v1.34.0
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "run.ai/simulated-gpu-node-pool=default"