name: Running E2E tests for AI Conformance

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run AI Conformance Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Build image
        run: |
          make image-build
  
      - name: Run E2E tests
        run: |
          make test-e2e

      - name: Run E2E tests via hydrophone
        run: |
          make test-hydrophone

      - name: Run E2E tests via Sonobuoy
        run: |
          make test-sonobuoy

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /tmp/results
          retention-days: 1
