name: "Running E2E tests for AI Conformance via Hydrophone"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run AI Conformance Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Run E2E tests via hydrophone
        run: |
          make test-hydrophone

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-hydrophone-results
          path: /tmp/results
          retention-days: 1
